### ISSUE TITLE
add integration-test with epic executions

### ISSUE THREAD

**Issue by BuckarooBanzay** [damocles-minetest/epic#17]
## To test

* [ ] Simple execution (start -> message)
* [ ] Branching

## Open issues

* [ ] Testing without player online?
* [ ] Intercept chat messages / teleport?
